# .github/FUNDING.yml içeriği

# Eğer Stripe destekli ülkede bir hesabın varsa:
github: [erogluyusuf]

# Türkiye'de en çok kullanılan alternatifler:
# patreon: patreon_kullanici_adin
ko_fi: erogluyusuf
# tidelift: platform-name
# issuehunt: username
# lfx_crowdfunding: project-name-at-lfx
custom: ["https://www.buymeacoffee.com/yusuferoglt"]
