name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Display hello message
        run: echo "Hello, this job has run successfully!"

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      
      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run fetch-repos script
        run: |
          npm install
          node fetch-repos.js
          
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "yusuferoglu1957@gmail.com"
          git add README.md
          git commit -m "README updated"
          git push
